### PR TITLE
Flag Added!

### PR DESCRIPTION
**Pull request by prdp1137**

### CODE REVIEW

**Review by TheBinitGhimire — CHANGES_REQUESTED** [review]
Hi @pr0d33p,

You did a great work with solving the challenge. Would you mind adding the write-ups as well on how you did it?

Thanks,
@TheBinitGhimire

**Comment by prdp1137** [comment]
# Writeup

First of all I downloaded the binary using `wget https://github.com/Hacktoberfest-Nepal/Hacktoberfest_CTF/raw/master/Reversing/beginners/Twine/Twine`, marked it as executable, ` chmod +x ./Twine ` entered random password and got false positive flag.

Later, I ran `strings ./Twine` and got a string of `y0u_g0t_17`. So, I used this as password and got the flag to be **hacktoberfest_ctf{str1ngs_2_w1n}**

**Comment by Aju100** [comment]
@pr0d33p please talk with binit about submission and it's process. it's being updated and we are sorry to inform in README

**Review by Aju100 — APPROVED** [review]

**Review by TheBinitGhimire — APPROVED** [review]

**Comment by naryal2580** [comment]
First of all, congratulations @pr0d33p for the flag!!

We are very sorry to let you know, that the following PR could not be approved. Your leakage of the flag has granted an excuse because you were not notified with the schedule of the challenge through the following PR cannot be merged. I am sorry.

You can send a PR after the CTF ends, and you can be a winner!!

Our team is apologizing to you again for the closing of this PR. Sorry..

**Pull request closed without merging**
